### ISSUE TITLE
"Session Storage" intro description is the same as "Cookie Sessions"

### ISSUE THREAD

**Issue by Jimmydalecleveland** [epicweb-dev/web-auth#3]
It looks like a new module was added that introduces session cookie interaction with toast notifications, but the overall description for the module is the same as the "Cookie Sessions" one (which I believe had some of this content previously)

It starts with this text:
> Storing user preferences is cookies is simple enough. If you check the developer tools for those, you'll often find the value as-is and can modify it using the developer tools (and sometimes even with JavaScript). For user preferences that's fine, but when it comes to authentication, we need to be more careful. Specifically, we need two things:

**Comment by kentcdodds** [comment]
Thank you for opening this issue! I'll get that fixed before the official launch of https://EpicWeb.dev :)
