### ISSUE TITLE
Toast notifications only work once when deleting notes

### ISSUE THREAD

**Issue by danielvanc** [epicweb-dev/web-auth#30]
When completing the Flash Storage lesson (problem) of the Session Storage module, I noticed when running the app that after you try deleting a note for the 2nd time (without doing a manual page reload), the toast notifications no longer work.

At the very end of the solution step, in the description, you created a utility for managing toast notifications (`redirectWithToast`), which appears to fix the above issue. It would be great if it could be explained, in the solution step, what the fix was to get that working correctly. 

Or perhaps update the problem exercise to have toast notifications working as expected without the utility? Whichever way you think works best for those learning :) 

Thanks allot and keep up the great work. 👍🏼

**Comment by kentcdodds** [comment]
Thank you! I've figured out what the problem was and added a note in the solution: https://github.com/epicweb-dev/web-auth/commit/9cbec1e69f5beeba1e1a53b29feb93684ab60b7e

Thanks a lot!
