### ISSUE TITLE
[Bug] routes for problem set 15 are bugged

### ISSUE THREAD

**Issue by cavacado** [epicweb-dev/web-auth#47]
Hi there, thanks for this workshop, i've been enjoying my time with it so far.

I would like to raise an issue about bugged routes for problem set 15 (Verify 2fa code).
I am able to navigate to `/15/01/problem` and am able to set the playground with the playground button.

However, upon closer inspection after setting the playground, the code for the playground app is actually the app of `/14/01/problem` instead.

Furthermore, if you try to navigate to the next page `/15/01/solution` via the UI, it instead navigates you to `14/01/solution`.

https://github.com/epicweb-dev/web-auth/assets/21698179/4cf994be-5b21-4caf-adee-ab6f2ead21a4

realised that under playground tab, there isnt any workshop 15, it just skips from 14 to 16:

<img width="1171" alt="Screenshot 2024-03-30 at 10 40 31" src="https://github.com/epicweb-dev/web-auth/assets/21698179/b08391ae-6c72-4fe9-9a5c-136f27b87b98">

**Comment by kentcdodds** [comment]
I have reproduced this. I'm not sure what's wrong, but I'll look into it. Thanks for opening the bug!

**Comment by kentcdodds** [comment]
Figured out the problem (it was a bad regex 🙃). Fix has been published. You should be able to get the latest fix with:

```
npx update-epic-workshop
```

Thanks again for reporting this!
