### ISSUE TITLE
[Bug]: incomplete condition to check for localhost network

### ISSUE THREAD

**Issue by lytovka** [epicweb-dev/web-auth#49]
Thanks a ton for the workshop material! I've had a great time digging into the intricacies of web auth.

I noticed a small issue while working on the Verification Module, Generate TOTP step (11/02). If I run my app on the local network (e.g., `http://192.168.xxx.xxx:port`) and use the [`getDomainUrl`](https://github.com/epicweb-dev/web-auth/blob/6d9f1b573437940303e293438120a10c3613aea4/exercises/11.verification/02.problem.totp/app/utils/misc.tsx#L34-L42) util, the raw IP address does not pass the localhost condition. Because of that, the `https` protocol is appended instead of `http`, which leads to a `ERR_SSL_PROTOCOL_ERROR` when I redirect to the `/verify` page.

I was able to get around this by extending the condition, though this makes the utility slightly more complicated:

```diff
-	const protocol = host.includes('localhost') ? 'http' : 'https'
+       const isLocalHost = host.includes('localhost') || /^192\.168\.\d{1,3}\.\d{1,3}/.test(host)
+	const protocol = isLocalHost ? 'http' : 'https'
```

**Comment by kentcdodds** [comment]
There's a lot that the condition misses (127.* etc). Every LAN is going to have a different setup as well so we'll never be able to tell with perfect accuracy from the `host` whether to use `https`, but we could do this instead:

```ts
export function getDomainUrl(request: Request) {
	const host =
		request.headers.get('X-Forwarded-Host') ?? request.headers.get('host')
	if (!host) {
		throw new Error('Could not determine domain URL.')
	}
	const protocol = request.headers.get('X-Forwarded-Proto') ?? 'http'
	return `${protocol}://${host}`
}
```

That should do a better job I think.

**Comment by kentcdodds** [comment]
I've updated the epic stack to do this: https://github.com/epicweb-dev/epic-stack/commit/4d7a674bb9237799ab4514ceaa77143342082ba5

I'll go through and update the workshops to do this as well.
