### ISSUE TITLE
Missing code from video?

### ISSUE THREAD

**Issue by RobbertWolfs** [epicweb-dev/web-auth#57]
https://github.com/epicweb-dev/web-auth/blob/001e398941e856d533597cfd895a8516c3acb051/exercises/11.verification/01.solution.schema/prisma/seed.ts#L27-L31

![image](https://github.com/user-attachments/assets/b224e753-b927-4780-b042-1b5e1c3ea824)

I noticed in the video of this exercise you had some extra code (and mentioned it) that is not inside this exercise (anymore)? 
Is there a reason its deleted and not needed anymore?
I was just wondering 😅

Also I cant remember we added those deletes for permissions and roles in previous exercises 🫣

**Comment by kentcdodds** [comment]
Good catch! I've added a note to explain why this happened.
